version: '3.7'
services:
  app:
    context: .
    dockerfile: Dockerfile
    args:
      DATABASEHOST: localhost
  ports:
    - '3000:3000'
  container_name: 'sistemarentad'
  volumes:
    - ./dist:/app/dist