name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute bash deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '52.15.146.227'
          username: 'ubuntu'
          key: "MIIEpAIBAAKCAQEAxPd2EAiLH7tesutu2H0DhDWjOV7cECFNYBHLCm+/QIf8andN
+WkgUnR6t7Y2m90k8EclIybEcCV/MhwfvE1k3sfCrlbiVzM6S4tGQ+PfAztQs/1x
Nu5uxSE8lAP1DHe31aui0n0U9E4vWciQKwFK1B+tIOoWDJ4bgIIVCkr7lMYTVFmk
dpwaDh3x1PO1iliLATgB+SO8tn2XhTD5LfYB/irzncxcIRGExcHA+3QIcG+04Yzq
uZ14YCrfjLFHBDwkhnDa/TgQby9dvVwKE79xzhRJ2nqEr6WL7n7yYv3PERs4uxiz
7YMV5xFrutLk9IraVz05PpKZjnY+Myv0XCHGMQIDAQABAoIBAQCUqRF62Hfo40p+
UCPBUdmtl64yRt5hbkEwGT3eCqmW0ww4bwNzE11J3pAgyG4/BZIzp/7noQLygdqW
v5NUVDWlz6+oVftPRWLiUaQe6YYQslwe/VLN2vfP4V4PeU0is9kUdA7YP3/pRHmI
kk/9pWQM5juNdCBgNZUcURIASsfHaMUpU+sxs7ARYpg/ocrbM9mffpStO7ZGVH79
lTlCGE9qLpJROYheI1ak9iZh+mvvDyMYoaJ7CvquNGP7uxBJA7KNYOQMes67DcD7
XvsPzs9jKxhSQD+2gHt1Tr0xLGZKCVP4ukTknGkVGD0nE1Q9Fqks5dIMS48zaRCN
ZHU53k1hAoGBAOs45kKXbR18ChlEkbZp/Pq6hUUhP+EwVwu8OH7YdS9DAQBOaTzj
WbNLIwaVSDEszWLRfBAdn6PhXNC/ckRY8pF37JG95Mvl0r7yCvE57O+ZCUs2bicR
PkCdwkLNnhpwPeKEFrHQLRBHOJunuyCDWsNxek650Sz0FMerVo9pDz7jAoGBANZd
e/iNf+FswkWcNrd4zZCXD9/vHZkE1P6LtmdAFtznT5AwunnVnA2N7kn8q4qJAtJf
3jNwEz9k2XlVTdqHFG9R0lMyqV8BM+ZAXZvxFOIWmShOi+EftOqQ5tJyLB6BkLVk
RXeqeZmNdO9hIvh8D+LgN+3HTc58sVoYGZ1EdD7bAoGBAL8gPaCQL94MQpxjZc6F
ckQ8ODuCl8gfIitr5a/Tq+waEn8wNzx9Mw6HF8+qjr0+PSh1NMxXdbaQUH1hgbRd
XcOrYPLPDFBMzp/ORevZ+FZ6z91oPbrKvP198jGbp0KuPuqGD3atw1/9rtZzRI5X
jPFPjGTZgUh4j0XqR2xBnlynAoGAW2fHWee0NMI0YIxIxJkNRm8zhLAoNbxauiOG
5qXsWcuEIJ62lQbhoOH5TrEf0FW1z1CzpclPW8O7+8HFDb51lzYTcghzMiCIKdEe
WUVGO1WZfxdnC9qCQVcCJZArgeKLet1Dxc/6Q+COkRghWkVEXOBw2MIYSkjfMuR9
35J14usCgYAysJWHq9zbbNG3PZsRMPTuEsLGLm5iW9IVMfLfIPrc8GIwnPo06MoL
fTU9GtiqC5VNNszHgstdVSpswKjkVkO+59pk3Oa0J3jiOz8pAJDuW2qxBoIwC3NU
sC6VD6nSqEo3nzL8N8PJyYTKDCtu5zZd+XelWFYdI8e3+wn2AIBYNQ=="
          script: whoami
