name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Execute bash deploy
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SECRET }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2:/home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2"
            echo "Kill Running PM2"
            pm2 delete sistemarenta
            cd /home/proyects/sistemarenta/
            git pull origin main
            sudo rm -rf node_modules
            yarn install
            yarn build
            cd /home/proyect/
            pm2 start ecosystem.config.js
          '
